spring:
  application:
    name: minecraft-status-api
  profiles:
    active:
      - "dev"
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      auto-index-creation: true
  devtools:
    add-properties: false
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
